CREATE TABLE user_books(
    ID INT NOT NULL AUTO_INCREMENT,
    ownerId INT NOT NULL,
    bookId INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ownerId) REFERENCES users(ID),
    FOREIGN KEY (bookId) REFERENCES books(ID)
)